RedHatInsights/uhc-auth-proxy

- server/server.go
- server/server_test.go
Warming up with minor changes - error responses to aid troubleshooting and error logging client side.
> Add response error text

- server/server.go
* Cost management & Marketplace operators can utilize insights-operator flow to validate with UHC
> Allow additional operators to utilize the uhc-proxy-flow

- openshift/uhc-auth-proxy-template.yaml
- Convert DeploymentConfig to Deployment
- Add deployment options recommended by app-sre
- Add service resource
> Updates to openshift deployment template

- openshift/uhc-auth-proxy-template.yaml
> v4 env requires memory request:limit ratio <2.0

- openshift/uhc-auth-proxy-template.yaml
> Add live/ready check on new /status endpoint

- requests/client/access.go
> Pull out svc account change pending account update

- openshift/uhc-auth-proxy-template.yaml
> Make openshift api endpoint configurable

- README.md
> Clean up documentation and clarify new functionality

- README.md
> Further documentation changes from mfindra

- grafana/dashboards/grafana-dashboard-insights-uhc-auth-proxy-health.configmap.yaml
> Update and clarify grafana dash

- Dockerfile
for executable base image use registry.access.redhat.com and for service image use the ubi minimal
> Dockerfile updated - base image changed

- server/server.go
- server/server_test.go
- To enable using that as a user-agent.
> add openshift lightspeed operator prefix

- cmd/root.go
- cmd/run.go
- cmd/start.go
this PR contains output from 
`go fmt ./...`
> format the source code via 'go fmt'

- .tekton/uhc-auth-proxy-pull-request.yaml
- .tekton/uhc-auth-proxy-push.yaml
Update default variable to true to build source image based on guide to konflux migration: https://gitlab.cee.redhat.com/konflux/docs/users/-/blob/main/topics/getting-started/components-applications.md#set-up-source-build-image
> Konflux Migration: Update default variable to true to build source image

- Dockerfile
[RHCLOUD-35258](https://issues.redhat.com/browse/RHCLOUD-35258)
> [RHCLOUD-35258] migrate the base images to the ubi9

- server/server.go
- server/server_test.go
Add JWS operator prefix to enable using that as an user-agent.
> Add JWS operator prefix

- .github/workflows/json-yaml-validation.yml
[RHCLOUD-37227](https://issues.redhat.com/browse/RHCLOUD-37227)
> [RHCLOUD-37227] add json and yaml basic validator into ci

- .github/workflows/golangci-lint.yml
- logger/logger.go
- requests/cluster/cluster.go
- server/server.go
- server/server_test.go
[RHCLOUD-36619](https://issues.redhat.com/browse/RHCLOUD-36619)
> [RHCLOUD-36619] add golangci-lint github action into repository

- Dockerfile
Ticket:
https://issues.redhat.com/browse/RHCLOUD-35258
Bump from ubi8 to ubi9
> RHCLOUD-35258 - UHC Auth Proxy ubi9-min update

- .tekton/uhc-auth-proxy-pull-request.yaml
- .tekton/uhc-auth-proxy-push.yaml
Reverts RedHatInsights/uhc-auth-proxy#192
> Revert "Konflux build pipeline service account migration"
