server/server.go

Nothing really needs to be exposed for status, just need an endpoint for
the checks to hit

Add basic status endpoint for Shift live/ready checks

---

Dockerfile

golang:alpine is no longer available for this build, but
rhel8/go-toolset:latest seems to include the same tools, though it
requires a privilege escalation during `go get`

Deploys in v4 now require RH registry images

---

openshift/uhc-auth-proxy-template.yaml

Added the parameter "REPLICAS" to "openshift/uhc-auth-proxy-template.yaml" and defined the variable as " 1 " (Which is was the original value before this modification). 
With the parameter above, we can now more easily define a custom number of pods in a deployment configuration.

Added the REPLICA parameter to the UHC-AUTH-PROXY template

---

README.md

I'm working on a schema for the identity header, and noticed the README needed
to be updated here to reflect the correct type capitalization of the `type` on the
identity: https://github.com/RedHatInsights/uhc-auth-proxy/blob/3fd2153a61128f0dddf067478ce369f9b7c1c471/requests/cluster/cluster.go#L41

Fix README capitalization

---

README.md
server/server.go
server/server_test.go

To test this PR, start the service locally, and send a curl request:
```
curl http://localhost:8080/api/uhc-auth-proxy/v1/ -A 'foo-operator/blah cluster/123' -H 'Authorization: Bearer foo'
```
You should get a 400 with an error similar to: `Invalid user-agent: 'Invalid user-agent: foo-operator/blah cluster/123'`
Now send a curl with:
```
curl http://localhost:8080/api/uhc-auth-proxy/v1/ -A 'acm-operator/blah cluster/123' -H 'Authorization: Bearer foo'
```
You should see a 401 now regarding the JWT auth not being valid, since it allowed the User Agent.
You can also run the updated unit tests with `go test -v ./...`
---
**Commit 2e5f10e**
https://issues.redhat.com/browse/RHCLOUD-14014
We need to support the following user agent value in 3scale/uhc-auth-proxy:
```
acm-operator/* cluster/* …
```

Allow acm operator user agent

---

server/server.go
server/server_test.go

This adds a test to exploit a situation where you can cause the system to panic
and throw a 500, when the User Agent slice does not contain at least two substrings.
For instance, the following will currently cause a panic/500, since the expected
`cluster/` portion of the agent string is missing:
```
curl http://localhost:8080/api/uhc-auth-proxy/v1/ -A 'foo-operator/blah' -H 'Authorization: Bearer foo'
```
This resolves the issue by checking if ` cluster/*` is in the agent prior to
accessing the slice by index. We also remove duplication for returning the same error on the User Agent checks.

Ensure we check the length of the User Agent before access by index

---

cmd/root.go
cmd/run.go
cmd/start.go
requests/client/wrapper.go
requests/cluster/cluster.go
requests/cluster/cluster_test.go
requests/cluster/config.go
requests/cluster/types.go
server/server.go
server/server_test.go

Big commit here, but it's all part of the same work. OCM has set up a
new tokenauth endpoint for us that will accept posts of a cluster id and
auth token. This will both clean up their metrics and drop our required
API calls from three to one to get the same data.

Remove OAT and post id:token to new endpoint

---

Dockerfile
unit_test.sh

---
- Updating the `Manual Build` comment within the `Dockerfile` to trigger a new image to be created in Quay.
- Additionally, I updated the `unit_test.sh` based on the newest build of Bonfire. So it is working again.

Manually Triggering Image Build and Unit Test Update

---

README.md
requests/cluster/cluster.go
requests/cluster/cluster_test.go
requests/cluster/types.go

- [Ensure we add the org_id in the top level of the UHC-auth identity](https://github.com/RedHatInsights/uhc-auth-proxy/commit/2260e14adc92facf5c2a2c76d88cd0191617fa16)
- [Add org_id to the README identity example](https://github.com/RedHatInsights/uhc-auth-proxy/commit/5d63012d368280beab814ff65747bc42293718c4)

Add top level org id support

---

server/server.go
server/server_test.go

This PR adds that support by allowing `assisted-installer-operator` as a valid operator prefix, and adds tests to exercise the changes.
Part of the effort to collect on-premises data from assisted-service https://issues.redhat.com/browse/MGMT-12483
Epic: https://issues.redhat.com/browse/MGMT-10308

Add `assisted-installer-operator/*` User-Agent

---

server/server.go
server/server_test.go

This PR adds the [Cryostat Operator](https://github.com/cryostatio/cryostat-operator) as an accepted prefix for a User-Agent string. In addition to its primary purpose as a JDK Flight Recorder based profiling and monitoring tool, an upcoming release of the Red Hat build of Cryostat adds support to assist sending reports to Red Hat Insights for Red Hat Runtimes products. [1]
As part of this support, the Cryostat Operator acts as a proxy. It receives payloads from Java agents deployed across the cluster and forwards them to Insights using the cluster's `cloud.openshift.com` token and cluster ID.
[1] https://github.com/RedHatInsights/insights-java-client

Add Cryostat Operator User-Agent

---

Dockerfile

Jira [RHCLOUD-32450](https://issues.redhat.com/browse/RHCLOUD-32450)
use the ubi9 images to solve the vulnerability in ubi8
```
quay.io/cloudservices/uhc-auth-proxy:d599035
NAME    INSTALLED         FIXED-IN            TYPE  VULNERABILITY   SEVERITY 
gnutls  3.6.16-8.el8_9.1  0:3.6.16-8.el8_9.3  rpm   CVE-2024-28834  Medium
```
with ubi9 (tested locally)
```
$ podman build -t uhc-auth-proxy:v1 .
...
$ grype --only-fixed localhost/uhc-auth-proxy:v1
...
No vulnerabilities found
```

[RHCLOUD-32450] use the latest ubi9/go-toolset and ubi9/ubi-minimal in Dockerfile

---

Dockerfile

This reverts commit 3be8d87af904f288a5cb3fe3f4d944f111053974
https://github.com/RedHatInsights/uhc-auth-proxy/pull/57
[RHCLOUD-32450](https://issues.redhat.com/browse/RHCLOUD-32450)
we cannot use ubi9 because the ubi8 is only one base image approved by our federal customers

[RHCLOUD-32450] Revert "use the latest ubi9/go-toolset and ubi9/ubi-minimal in Dockerfile

---

grafana/dashboards/grafana-dashboard-insights-uhc-auth-proxy-health.configmap.yaml

[RHCLOUD-32590](https://issues.redhat.com/browse/RHCLOUD-32590)
grafana: https://grafana.stage.devshift.net/d/NncCcICiz/uhc-auth-proxy-health?orgId=1

[RHCLOUD-32590] uhc-auth-proxy grafana update - solve warning about deprecated graph type

---

openshift/uhc-auth-proxy-template.yaml

[RHCLOUD-32616](https://issues.redhat.com/browse/RHCLOUD-32616)
according long term observation we can lower limits and requests values for cpu and memory
https://grafana.stage.devshift.net/d/HXbU7G1Iz/aandm-resources-health?orgId=1&from=now-7d&to=now&var-Datasource=crcp01ue1-prometheus

[RHCLOUD-32616] updated limits and requests for cpu and memory for uhc auth proxy containers

---

openshift/uhc-auth-proxy-template.yaml

[RHCLOUD-32987](https://issues.redhat.com/browse/RHCLOUD-32987)
our cpu limit utilisation is 2 %, I think we can update the values a little bit
https://grafana.stage.devshift.net/d/R-Q6WgAIz/insights-resource-queries?orgId=1&from=now-7d&to=now&var-datasource=P5FEA9F8380B21C0A&var-namespace=uhc-auth-proxy-prod&var-pod=All&var-rds_datasource=P465885893AA82E04&var-db_instance=

[RHCLOUD-32987] updated limit and request for cpu resource

---

go.mod
go.sum

upgrade github.com/go-chi/chi/v5 to the latest version
(and as a bonus new image with latest base image will be generated)

[RHCLOUD-33855] bump go-chi/chi/v5 to the latest version

---

requests/client/access.go
requests/client/wrapper.go
server/server_test.go

[RHCLOUD-33914](https://issues.redhat.com/browse/RHCLOUD-33914)
ioutil.ReadAll is deprecated: As of Go 1.16, this function simply calls io.ReadAll. https://pkg.go.dev/io/ioutil#ReadAll

[RHCLOUD-33914] change ioutil.ReadAll into io.ReadAll

---

.tekton/uhc-auth-proxy-pull-request.yaml
konflux_unit_test.sh

Adding the tasks to run the unit test within the tekton build pipelines

Add unit tests to uhc-auth-proxy build pipeline

---

Dockerfile

This reverts commit 761e22f703c56086c78c3a90c138d744f3152212. 
Because of the FEDRAMP requirement we need to migrate back to the ubi8.

Revert "migrate the base images to the ubi9"

---

go.mod
go.sum

[RHCLOUD-36127](https://issues.redhat.com/browse/RHCLOUD-36127)
upgrade `github.com/aws/aws-sdk-go` package to the latest version => generate new image with latest base image and fix some vulnerabilities
```
NAME          INSTALLED          FIXED-IN            TYPE       VULNERABILITY   SEVERITY 
bzip2-libs    1.0.6-26.el8       0:1.0.6-27.el8_10   rpm        CVE-2019-12900  Low       
krb5-libs     1.18.2-29.el8_10   0:1.18.2-30.el8_10  rpm        CVE-2024-3596   High      
openssl-libs  1:1.1.1k-12.el8_9  1:1.1.1k-14.el8_6   rpm        CVE-2024-5535   Low       
stdlib        go1.21.13          1.22.7, 1.23.1      go-module  CVE-2024-34158  High      
stdlib        go1.21.13          1.22.7, 1.23.1      go-module  CVE-2024-34156  High      
stdlib        go1.21.13          1.22.7, …
```

[RHCLOUD-36127] upgrade github.com/aws/aws-sdk-go package to the latest version

---

.dockerignore

[RHCLOUD-32031](https://issues.redhat.com/browse/RHCLOUD-32031)
one of recommendations in [Credential Leak Self Assessment](https://docs.google.com/document/d/1IsX7NmMnWPcuOseyjjUj_T9VjBXx7p3UjWs5eNpDHyI/edit?tab=t.0) document is to add `.dockerignore` file into repository and not ignore only files and folders that are needed

[RHCLOUD-32031] update dockerignore

---

.tekton/uhc-auth-proxy-pull-request.yaml
Dockerfile

[RHCLOUD-37582](https://issues.redhat.com/browse/RHCLOUD-37582)
base image ubi8/ubi-minimal in the RH catalog: https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?container-tabs=overview
this change will enable the Konflux Bot to automatically detect when a new base image version is released and create a PR for the update and we will have better control over the base image version

[RHCLOUD-37582] specify the base image version in the dockerfile

---

.tekton/uhc-auth-proxy-pull-request.yaml

we migrated into ubi9 here https://github.com/RedHatInsights/uhc-auth-proxy/pull/125
but forgot to update the tekton config too

migrate to the ubi9/ubi-minimal base image in the tekton config

---

.github/workflows/golangci-lint.yml
go.mod
go.sum

[RHCLOUD-38588](https://issues.redhat.com/browse/RHCLOUD-38588)

[RHCLOUD-38588] upgrade go version into 1.21

---

.github/workflows/golangci-lint.yml
go.mod

[RHCLOUD-38634](https://issues.redhat.com/browse/RHCLOUD-38634)

[RHCLOUD-38634] upgrade go version into 1.22.9 (latest in the ubi9/go-toolset base image)

---

.tekton/uhc-auth-proxy-pull-request.yaml
.tekton/uhc-auth-proxy-push.yaml

https://issues.redhat.com/browse/KONFLUX-2264
Context:
Related slack thread: https://redhat-internal.slack.com/archives/C059NUD49PD/p1742912856679589
-  there are new checks required to be added to konflux pipelines in order to pass the enterprise contract
- these checks are required to be installed by April 1st.

Add shell and unicode sast pipeline tasks

---

.tekton/uhc-auth-proxy-pull-request.yaml
.tekton/uhc-auth-proxy-push.yaml

Related PR: https://github.com/RedHatInsights/uhc-auth-proxy/pull/192/files
I had to revert this mentioned PR because Konflux had accidentally deleted most of our push pipeline and this PR is manually updating our tekton pipelines with the new information

[KONFLUX] Update tekton pipelines for konflux with new service account

---

.tekton/uhc-auth-proxy-pull-request.yaml

`enterprise-contract `pipeline is failing because of 
```
✕ [Violation] tasks.required_untrusted_task_found
ImageRef: quay.io/redhat-user-workloads/hcc-accessmanagement-tenant/uhc-auth-proxy/uhc-auth-proxy@sha256:da2b6605a709316d5dd05a7c4fed5ee97b7ee773f2c0db3b0ed76c16bbbaba6c
Reason: Required task "git-clone-oci-ta" is required and present but not from a trusted task
Term: git-clone-oci-ta
Title: All required tasks are from trusted tasks
Description: Ensure that the all required tasks are resolved from trusted tasks. To exclude this rule add
"tasks.required_untrusted_task_found:git-clone-oci-ta" to the `exclude` section of the policy configuration.
Solution: Make sure all required tasks in the build pipeline are resolved from trusted tasks.
```

update 'task-git-clone-oci-ta' ref to the latest version
